### ISSUE TITLE
Please update.

### ISSUE THREAD

**Issue by cknost** [Bluscream/TS3AudioBotPlugins#1]
Not Working on the New Version.

**Comment by cknost** [comment]
What??! While invaild?

**Comment by cknost** [comment]
https://github.com/Splamy/TS3AudioBot/issues/281

**Comment by Bluscream** [comment]
oh lol, i thought wrong repo, sorry

**Comment by Bluscream** [comment]
tbh i am absolutely not in the mood to fix them. If you want to PR, you're welcome :)

**Comment by Bluscream** [comment]
Done.
