### ISSUE TITLE
Youtube Search

### ISSUE THREAD

**Issue by Bertigrad** [Bluscream/TS3AudioBotPlugins#18]
Im Load Youtube Search Plugins Folder
And !plugin load YoutubeSearchPlugin.dll
and !yt Search music but Error An unexpected error occured: Could not load file or assembly 'YoutubeSearch, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Sistem belirtilen dosyayı bulamıyor.

**Comment by Bluscream** [comment]
You need youtubesearch dll

**Comment by Bertigrad** [comment]
can you give me and ı where install

**Comment by Bluscream** [comment]
https://puu.sh/DFvSB/a540fa6b40.dll save it as `YoutubeSearch.dll` in TS3AB root folder

**Comment by Bertigrad** [comment]
ı cant play music plugin

**Comment by Bertigrad** [comment]
do you give me open source code

**Comment by Bertigrad** [comment]
http://prntscr.com/o1kfx4

**Comment by Bluscream** [comment]
That has nothing to do with my plugin, closing

**Comment by Bertigrad** [comment]
Please dont give open source code okey but give me youtube play plugin

**Comment by Bluscream** [comment]
It is here in this repo

**Comment by Bluscream** [comment]
Ask @splamy about that internal error thingy

**Comment by Bertigrad** [comment]
Thanks for help me
