### ISSUE TITLE
Develop

### ISSUE THREAD

**Issue by Bertigrad** [Bluscream/TS3AudioBotPlugins#19]
does not open in open source visual studio have error

**Comment by Bertigrad** [comment]
msbuild

**Comment by Bluscream** [comment]
Error?

**Comment by Bertigrad** [comment]
C:\Users\memati\Desktop\TS3AudioBotPlugins-develop\Follow\AutoFollow.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\memati\Desktop\TS3AudioBotPlugins-develop\Follow\AutoFollow.csproj

**Comment by Bertigrad** [comment]
help please

**Comment by Bluscream** [comment]
Try visual Studio 2019
